apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  namespace: three-tier
spec:
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    nodePort: 30001  # Optional: You can specify a custom nodePort within the range 30000-32767
  type: NodePort
  selector:
    role: frontend
